### ISSUE TITLE
Download failed :(

### ISSUE THREAD

**Issue by shaolin-peanut** [pruiz-ca/matryoshka#1]
### Bug 🐞

The error message is in the title, with no additional context, so I don't what failed exactly. Will investigate and add to this thread.

### Steps to Reproduce:

1. clone the repo
2. install matryoska
3. run `matryoshka run`

**Comment by pruiz-ca** [comment]
Hello, I haven't used this in 3 years and won't use it. I'm using this docker image instead: https://hub.docker.com/r/pruizca/42img/

**Comment by shaolin-peanut** [comment]
nice, I'm gonna use that as I realized I can use docker as well for the advanced projects I wanna do
